# PostgreSQL
database:
  name: "passwall"
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  logmod: false

server:
  port: "3625"
  username: "passwall"
  password: "password"
  passphrase: "passphrase-for-encrypting-passwords-do-not-forget"
  secret: "secret-key-for-JWT-TOKEN"
  timeout: 24 # Token duration in hours format
  generatedPasswordLength: 16 # Minimum 4
  accessTokenExpireDuration: "50m"  # Example: 29m, 2h, 9d
  refreshTokenExpireDuration: "25d"  # Example: 57m, 5h, 7d

backup:
  folder: "./store" # you can feel free to change any where your in project 
  rotation: 7 # backup rotation
  period: "24h" # backup period. Example: 12h, 3h15m, 8h20m30s